fstName=input("First Name: ")
mdlName=input("Middle Name: ")
lstName=input("Last Name: ")
fullName= "{} {} {}".format(fstName, mdlName, lstName)
print("Full Name: ", fullName)
age=int(input("Age: "))
branch=input("Branch: ")
detail= "{} {} {}".format(fullName,age,branch)
print("Detail: ", detail)